# Generated by Django 5.0.6 on 2024-07-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanningCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planningCropId', models.IntegerField()),
                ('plantingDate', models.DateTimeField()),
                ('harvestDate', models.DateTimeField()),
                ('cropYield', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
                ('cropCropId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('locationDescription', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('cropCropId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.crop')),
                ('farmFarmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentId', models.IntegerField()),
                ('incidentType', models.CharField(max_length=100)),
                ('incidentDescription', models.CharField(max_length=100)),
                ('responseAction', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('plotPlotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plot')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmentalId', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('soilNutrient', models.FloatField()),
                ('sunIntensity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('airHumidity', models.FloatField()),
                ('createdAt', models.DateTimeField()),
                ('plotPlotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plot')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionId', models.IntegerField()),
                ('actionType', models.CharField(max_length=100)),
                ('actionDescription', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('incidentIncidentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.incident')),
                ('plotPlotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plot')),
            ],
        ),
    ]
